exchange:
  api:
    base-url: https://api.apilayer.com/exchangerates_data
    api-key: O4RVixbbV78XBQs9ChDKfRzjEgrZqaM5
  executor:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 100
    keep-alive-seconds: 60
  cache:
    expiration-hours: 1
    maximum-size: 100

spring:
  cloud:
    openfeign:
      client:
        config:
          exchangeApiClient:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: basic
            default-request-headers:
              apiKey: ${exchange.api.api-key}
  datasource:
    url: jdbc:mysql://localhost:3306/exchange-api
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: jankowalksiii12@gmail.com
    password: ypvx ehmk tmjk ktkj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


