exchange:

  api:
    base-url: https://api.apilayer.com/exchangerates_data
    api-key: kRDWpYN2kuwD0130FZBvUY3jJ6UJrQKi

  async:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 25
    thread-name-prefix: "EmailSender-"
    wait-for-tasks-to-complete-on-shutdown: true
    rejection-policy: "CALLER_RUNS"

cache:
  expiration-hours: 1
  maximum-size: 100

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: jankowalksiii12@gmail.com
    password: ypvx ehmk tmjk ktkj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    users:
      - username: user
        password: '{noop}user'
        roles: USER
      - username: admin
        password: '{noop}admin'
        roles: USER,ADMIN